# Generated by Django 3.2.9 on 2022-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_wallet_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_Users_wallet_friends_+', to='Users.Wallet'),
        ),
    ]
