# Generated by Django 3.2.9 on 2022-04-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_wallet_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
