# Generated by Django 3.2.9 on 2021-12-29 18:25

import Chat.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=240)),
                ('profile', models.ImageField(blank=True, upload_to=Chat.utils.upload_profilepic)),
                ('type', models.CharField(choices=[['C', 'Channel'], ['G', 'Group'], ['P', 'Private']], default='G', max_length=1)),
                ('slug', models.SlugField(blank=True, max_length=40)),
                ('temporaryLink', models.SlugField(blank=True, max_length=40)),
                ('temporaryLinkExpiredDate', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ManyToManyField(blank=True, related_name='admin_in_chats', to='Users.Wallet')),
                ('block', models.ManyToManyField(blank=True, related_name='blocked_in_chats', to='Users.Wallet')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_owner', to='Users.wallet')),
                ('users', models.ManyToManyField(blank=True, related_name='chat', to='Users.Wallet')),
            ],
        ),
        migrations.CreateModel(
            name='ReportReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=Chat.utils.upload_file)),
                ('message', models.CharField(max_length=2048)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Chat.chat')),
                ('hidden', models.ManyToManyField(blank=True, to='Users.Wallet')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Users.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='ReportChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='Chat.chat')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='Chat.reportreason')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='Users.wallet')),
            ],
            options={
                'unique_together': {('reporter', 'chat')},
            },
        ),
    ]
