# Generated by Django 3.2.9 on 2021-12-29 18:25

import Chat.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'Monday'), ('2', 'Tuesday'), ('3', 'Wednesday'), ('4', 'Thursday'), ('5', 'Friday'), ('6', 'Saturday'), ('7', 'Sunday')], max_length=1)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('image', models.ImageField(upload_to=Chat.utils.upload_banner)),
                ('status', models.CharField(blank=True, choices=[['A', 'Accept'], ['W', 'Waiting'], ['R', 'Reject']], default='W', max_length=1)),
                ('payed', models.BooleanField(default=False)),
                ('timeTable', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Banner.timetable')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.wallet')),
            ],
        ),
    ]
